server:
  port: 8081
spring:
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      password: axon1234
      lettuce:
        pool:
          max-active: ${SPRING_DATA_REDIS_LETTUCE_POOL_MAX_ACTIVE:8}
          max-idle: ${SPRING_DATA_REDIS_LETTUCE_POOL_MAX_IDLE:8}
          min-idle: ${SPRING_DATA_REDIS_LETTUCE_POOL_MIN_IDLE:0}
          max-wait: ${SPRING_DATA_REDIS_LETTUCE_POOL_MAX_WAIT:1000}ms
  profiles:
    include: oauth

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
    consumer:
      group-id: axon-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
jwt:
  secret: ${JWT_SECRET:YOUR_VERY_SECRET_RANDOM_STRING_THAT_IS_LONG_ENOUGH_axonskusw}

payment:
  token:
    secret: ${PAYMENT_TOKEN_SECRET:dev_payment_token_secret_key}

axon:
  core-service:
    base-url: http://localhost:8080

# Actuator and Metrics
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name:entry-service}

