services:
  core-service:
    environment:
      JAVA_TOOL_OPTIONS: ${CORE_JAVA_TOOL_OPTIONS:-}
    volumes:
      - ${PINPOINT_AGENT_DIR:-./pinpoint-agent}:/pinpoint-agent:ro

  entry-service:
    environment:
      JAVA_TOOL_OPTIONS: ${ENTRY_JAVA_TOOL_OPTIONS:-}
    volumes:
      - ${PINPOINT_AGENT_DIR:-./pinpoint-agent}:/pinpoint-agent:ro
